apiVersion : apps/v1
kind : Deployment
metadata : 
  name : mcp-deploy
  labels :
    app : mcp-app

spec :
  replicas : 4 
  selector :
    matchLabels :
      app : mcp-app
  template :
    metadata :
      labels :
        app : mcp-app 
    spec :
      containers :
        - name : mcp-container
          image : vishymails/mcp-deploy:1.0
          ports :
            - containerPort : 8000


